#!/bin/bash

[[ ! -d "/etc/wireguard/peer" ]] && mkdir -p /etc/wireguard/peer
cd /etc/wireguard
umask 077; wg genkey | tee serverprivatekey | wg pubkey > serverpublickey
echo "server keys generated!!!"
cd /etc/wireguard/peer
umask 077; wg genkey | tee clientprivatekey | wg pubkey > clientpublickey
umask 077; wg genpsk | tee clientpresharedkey
echo "client keys generated!!!"
cat << EOF > /etc/wireguard/wg0.conf
[Interface]
Address = 192.168.200.1/32
ListenPort = 65520
PrivateKey = $(cat /etc/wireguard/serverprivatekey)
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = $(cat /etc/wireguard/peer/clientpublickey)
PresharedKey = $(cat /etc/wireguard/peer/clientpresharedkey)
AllowedIPs = 192.168.200.2/32
EOF
cat /etc/wireguard/wg0.conf
echo "server config generated!!!"
cat << EOF > /etc/wireguard/peer/client.conf
[Interface]
Address = 192.168.200.2/24
PrivateKey = $(cat /etc/wireguard/peer/clientprivatekey)

[Peer]
Endpoint = $(curl http://ipecho.net/plain):65520
PersistentKeepalive = 5
AllowedIPs = 1.0.0.0/8, 2.0.0.0/8, 3.0.0.0/8, 4.0.0.0/6, 8.0.0.0/7, 11.0.0.0/8, 12.0.0.0/6, 16.0.0.0/4, 32.0.0.0/3, 64.0.0.0/2, 128.0.0.0/3, 160.0.0.0/5, 168.0.0.0/6, 172.0.0.0/12, 172.32.0.0/11, 172.64.0.0/10, 172.128.0.0/9, 173.0.0.0/8, 174.0.0.0/7, 176.0.0.0/4, 192.0.0.0/9, 192.128.0.0/11, 192.160.0.0/13, 192.169.0.0/16, 192.170.0.0/15, 192.172.0.0/14, 192.176.0.0/12, 192.192.0.0/10, 193.0.0.0/8, 194.0.0.0/7, 196.0.0.0/6, 200.0.0.0/5, 208.0.0.0/4, 192.168.200.0/24, 8.8.8.8/32
PresharedKey = $(cat /etc/wireguard/peer/clientpresharedkey)
PublicKey = $(cat /etc/wireguard/serverpublickey)
EOF
cat /etc/wireguard/peer/client.conf
echo "client config generated!!!"
qrencode -t ansiutf8 < /etc/wireguard/peer/client.conf
