#!/bin/bash

[[ ! -d "/etc/wireguard" ]] && mkdir -p /etc/wireguard/peer
cd /etc/wireguard
umask 077; wg genkey | tee serverprivatekey | wg pubkey > serverpublickey
echo "server keys generated!!!"
umask 077; wg genkey | tee /etc/wireguard/peer/clientprivatekey | wg pubkey > /etc/wireguard/peer/clientpublickey
umask 077; wg genpsk | tee /etc/wireguard/peer/clientpresharedkey
echo "one peer keys generated!!!"
sed "s/ServerPrivateKey/`cat /etc/wireguard/serverprivatekey`/g;s/ClientPublicKey/`cat /etc/wireguard/peer/clientpublickey`/g;s/ClientPSK/`cat /etc/wireguard/peer/clientpresharedkey`/g" /opt/wgs.conf.tmpl | tee /etc/wireguard/wg0.conf
sed "s/ClientPrivateKey/`cat /etc/wireguard/peer/clientprivatekey`/g;s/ClientPSK/`cat /etc/wireguard/peer/clientpresharedkey`/g;s/ServerPublicKey/`cat /etc/wireguard/serverpublickey`/g" /opt/wgs.conf.tmpl | tee /etc/wireguard/peer/client.conf
qrencode -t ansiutf8 < /etc/wireguard/peer/client.conf
