name: ovftool Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${{ secrets.ghcrtoken }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        cd ovftool
        docker build . --file Dockerfile --tag ovftool:latest
        docker images
        docker run --rm --name=ovftool -it ovftool:latest ovftool --help

    - name: push ghcr.io
      run: |
        docker tag ovftool:latest ghcr.io/skylens/ovftool:latest
        docker push ghcr.io/skylens/ovftool:latest
        
    - name: test
      run: |
       docker run --rm --name=ovftool -it ghcr.io/skylens/ovftool:latest ovftool --help
