name: musl-cross-x64 Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd musl-cross;docker build . --file Dockerfile --tag musl-cross-x64-builder:latest
    - name: push ghcr.io
      env:
        token: ${{ secrets.ghcrtoken }}
      run: |
        echo $token | docker login ghcr.io -u skylens --password-stdin
        docker tag musl-cross-x64-builder:latest ghcr.io/skylens/musl-cross-x64-builder:latest
        docker push ghcr.io/skylens/musl-cross-x64-builder:latest